FROM python:3.9

# 必要なライブラリをインストール
RUN apt-get update && \
    apt-get install -y libgl1-mesa-glx && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Pythonライブラリをインストール
RUN pip install opencv-python

WORKDIR /usr/src/app