services:
  python:
    build: ./docker/python
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app
    tty: true
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
    
